version: "3.8"

services:
  app:
    build: .
    restart: always
    stop_signal: SIGINT
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/mydb
    volumes:
      - C:/:/host-c

  postgres:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:


volumes:
  postgres-data: